### Users create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Derek Lewis",
  "email": "derek@email.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "sam@email.com",
  "password": "password"
}

### GAMES INDEX
GET http://localhost:3000/games.json

### GAMES SHOW
GET http://localhost:3000/games/1.json

### FAVORITES CREATE (nested)
POST http://localhost:3000/games/1/favorites.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NzU4ODI2NDh9.PPjYx7-RFDsNkLSrVgnwxb9wCYzbv1r2AhFabUbwimQ

### FAVORITES INDEX
GET http://localhost:3000/favorites.json
Authorization: Bearer 

### FAVORITES SHOW 
GET http://localhost:3000/favorites/1.json
Authorization: Bearer 

### FAVORITES CREATE
# POST http://localhost:3000/favorites.json
# Content-Type: application/json

# {
#   "user_id": 2,
#   "game_id": 2
# }

### FAVORITES DESTROY
DELETE http://localhost:3000/favorites/3.json